version: "2"
services:
  builder:
    image: openlmis/dev:5.2
    links:
      - db
      - log
    volumes:
      - '.:/app'
    command:
      - './build.sh'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    env_file: .env
  sonar:
    image: openlmis/dev:5.2
    volumes:
      - '.:/app'
    entrypoint:
      - 'gradle'
    command:
      - 'sonarqube'
    environment:
      GRADLE_OPTS: '-Dorg.gradle.daemon=false $SONAR_LOGIN $SONAR_PASSWORD'
    env_file: .env
  image:
    build: .
    image: openlmis/example
  example:
    image: openlmis/example
    links:
      - db
      - log
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: '-Dlogging.config=/logback.xml'
    volumes:
      - '../logback.xml:/logback.xml'
  db:
    image: openlmis/postgres:9.4
    ports:
      - "5432"
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/example:/var/log'
